# Generated by Django 5.0.4 on 2024-04-25 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_food_room_service_employee_foodorder_roombooking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
