# Generated by Django 5.0.4 on 2024-04-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_department_employee_role_employee_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
