# Generated by Django 5.0.4 on 2024-04-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_foodorder_total_price_service_service_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
