# Generated by Django 5.0.4 on 2024-04-26 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_service_service_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bill',
        ),
        migrations.AddField(
            model_name='foodorder',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='food_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.foodorder'),
        ),
        migrations.AddField(
            model_name='payment',
            name='service_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.serviceorder'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
