# Generated by Django 5.0.4 on 2024-04-26 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_payment_bill_foodorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
